### ISSUE TITLE
TypeError: array(#) is not JSON serializable

### ISSUE THREAD

**Issue by TheMacMini09** [matthiasvegh/Chunkymator#30]
Getting this error on Mac OS X 10.11. Full stacktrace is linked, as is the full log. Occurs whenever I try to select any scenes created by the newest Chunky - I haven't tried any other versions. Using the built-in python and libraries. A bit of googling seems as though the program is trying to convert a bumpy array into a JSON object - no idea if that's correct or accurate, but may be helpful in finding your problem. 

[Stacktrace](http://pastebin.com/1pXaXdYe)
[Log](http://pastebin.com/RjhjLeTw)

**Comment by matthiasvegh** [comment]
Thanks for the bug report, I just tried to reproduce this with scenes saved by Chunky 1.3.5 with no luck.  Based on the log you sent, it seems that something is up with the Y value, but I'm not sure yet. Could you post the jsons your trying to work with?

**Comment by TheMacMini09** [comment]
Certainly. They're linked [here](https://mega.nz/#F!G1VD1JLY!0Y8mlHKTJn9yUvKSFYM_1Q).

**Comment by matthiasvegh** [comment]
Thanks for the jsons, I tried running morph.py with them, but didn't encounter the symptoms you saw.
Can you post the version of python, scipy and numpy you're using?

    import numpy
    numpy.version.version

Issued in a python terminal would be great (likewise for scipy).
I've heard of issues with Chunkymator on platforms other than linux, but haven't really had the opportunity to figure them out, so any help you can provide would be great.

**Comment by matthiasvegh** [comment]
FWIW: On my Linux the output for

    ./morph.py /home/phil/sandbox/JSONs/JSONs/test1.json /home/phil/sandbox/JSONs/JSONs/test2.json /home/phil/sandbox/JSONs/JSONs/test3.json /home/phil/sandbox/JSONs/JSONs/test4.json

Is [this](http://pastebin.com/5uPNkfMx).

Info of my box:

    python --version
    Python 2.7.3

    >>> numpy.version.version
    '1.6.1'
    >>> scipy.version.version
    '0.9.0'

**Comment by TheMacMini09** [comment]
/usr/bin/python --version
    Python 2.7.6
    
    >>> import numpy
    >>> numpy.version.version
    '1.8.0rc1'
    >>> import scipy
    >>> scipy.version.version
    '0.13.0b1'

These are what came with the system, AFAIK.

**Comment by matthiasvegh** [comment]
I upgraded my scipy and numpy libraries (to 1.9.2 and 0.16.0 respectively) I can now see the problem you were tackling, I'll investigate and get back to you shortly.

**Comment by TheMacMini09** [comment]
Awesome, thanks!

**Comment by matthiasvegh** [comment]
I figured out the problem. A [breaking change was introduced in scipy](http://docs.scipy.org/doc/scipy-0.14.0/reference/release.0.11.0.html#minor-change-in-behavior-of-splev), which just ruined my day.
Anyway, I've pushed a commit to branch scipyupdate, if it solves this issue, I'll merge it into master.

**Comment by TheMacMini09** [comment]
>which just ruined my day
:(

Thankfully you've got that fixed. I'm cloning the new branch, I'll get back to you shortly.

**Comment by TheMacMini09** [comment]
Yep, that fixes it. Thanks!

**Comment by matthiasvegh** [comment]
Great! Merging. Let me know if you see anything else that causes you troubles.
